project/coplan/urls.py
from django.conf.urls import patterns, url, include
from . import api
from . import views

urlpatterns = patterns(
    'coplan',

    url(r'^$', views.homepage, name='home'),
    url(r'^plans/$', views.new_plan, name='new_plan'),
    url(r'^plans/(?P<pk>\d+)/$', views.edit_plan, name='edit_plan'),
    url(r'^users/(?P<pk>\d+)/profile/$', views.user_profile, name='user_profile'),

    url(r'^api/', 
        include('djangorestframework.urls', namespace='djangorestframework')),
    url('^api/v1/plans/$', 
        api.PlanListView.as_view(), name='plan_list'),
    url('^api/v1/plans/(?P<pk>\d+)$', 
        api.PlanInstanceView.as_view(), name='plan_instance'),
    url('^api/v1/plans/(?P<plan_id>\d+)/comments/$', 
        api.PlanCommentListView.as_view(), name='plan_comment_list'),
    url('^api/v1/plans/(?P<plan_id>\d+)/comments/(?P<pk>\d+)$', 
        api.PlanCommentInstanceView.as_view(), name='plan_comment_instance'),

)

project/project/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'project.views.home', name='home'),
    # url(r'^project/', include('project.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),

    url(r'', include('django.contrib.auth.urls')),

    url(r'^login-form/$', 'django.views.generic.simple.direct_to_template',
        {'template': 'login-form.html'}),
    url(r'', include('social_auth.urls')),

    url(r'^', include('coplan.urls')),
)

project/coplan/models.py
from django.db import models
from django.contrib.auth import models as auth


class Planner (auth.User):
    class Meta:
        proxy = True

    @property
    def avatar_url(self):
        from random import randint
        return ''.join(['/static/coplan/img/user', str(randint(1,4)), '.png'])

        
class Plan (models.Model):
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)
    
    title = models.CharField(max_length=100, null=True, blank=True)
    motivation = models.CharField(max_length=140, null=True, blank=True)
    details = models.TextField(null=True, blank=True)
    owner = models.ForeignKey('coplan.Planner', related_name='owned_plans')
    
    location_lat = models.FloatField(null=True, blank=True)
    location_lon = models.FloatField(null=True, blank=True)

    supporters = models.ManyToManyField('coplan.Planner', 
                                        related_name='supported_plans',
                                        through='coplan.Support',
                                        blank=True)


class Support (models.Model):
    MOTIVATION_CHOICES = (
        ('I live here', 'I live here'),
        ('I work here', 'I work here'),
        ('I play here', 'I play here'))
    supporter = models.ForeignKey('coplan.Planner', related_name='support')
    plan = models.ForeignKey('coplan.Plan', related_name='support')
    motivation = models.CharField(max_length=140, choices=MOTIVATION_CHOICES,
                                  help_text='What is your connection to the area?')

    class Meta:
        unique_together = [('supporter', 'plan'),]

    
class Link (models.Model):
    plan = models.ForeignKey('coplan.Plan', related_name='links')
    url = models.URLField()


# class Image (models.Model):
#     plan = models.ForeignKey('coplan.Plan', related_name='images')
#     data = models.ImageField()


class Video (models.Model):
    plan = models.ForeignKey('coplan.Plan', related_name='videos')
    url = models.URLField()

class Comment (models.Model):
    TYPE_CHOICES = (
        (1, 'Support'),
        (-1, 'Oppose'),
        (0, 'Question'))
    
    plan = models.ForeignKey('coplan.Plan', related_name='comments')
    commenter = models.ForeignKey('coplan.Planner', related_name='comments')
    text = models.TextField()
    type = models.IntegerField(choices=TYPE_CHOICES)
    created_datetime = models.DateTimeField(auto_now_add=True)

project/coplan/forms.py
from django import forms
from . import models

class PlanCommentForm (forms.ModelForm):
    """
    The form used to validate comments.  The plan and the commenter are 
    both implicit from the view.
    """
    class Meta:
        model = models.Comment
        exclude = ['plan', 'commenter']

project/coplan/views.py
import json
from django.contrib.auth.decorators import login_required
from django.contrib.auth import models as auth_models
from django.core.serializers.json import DateTimeAwareJSONEncoder
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from . import models
from . import resources

def homepage(request):
    featured_plans = [models.Plan.objects.get(pk=30), 
                      models.Plan.objects.get(pk=25),
                      models.Plan.objects.get(pk=40)]
    context = RequestContext(request, {
        'featured_plans': featured_plans
    })
    return render_to_response('index.html', context_instance=context)

@login_required
def new_plan(request):
    planner = models.Planner.objects.get(pk=request.user.pk)
    context = RequestContext(request, {
        'planner': planner,
    })
    return render_to_response('plan_detail.html', context_instance=context)


def edit_plan(request, pk):
    plan = get_object_or_404(models.Plan, pk=pk)

    if request.user.is_authenticated():
        planner = models.Planner.objects.get(pk=request.user.pk)
    else:
        planner = models.Planner()
        
    context = RequestContext(request, {
        'planner': planner,
        'plan': plan,
        'plan_data': json.dumps(resources.PlanResource().serialize(plan),
                                cls=DateTimeAwareJSONEncoder)
    })
    return render_to_response('plan_detail.html', context_instance=context)

def user_profile(request, pk):
    owner = get_object_or_404(auth_models.User, pk=pk)
    context = RequestContext(request, {
        'owner': owner
    })
    return render_to_response('user_profile.html', context_instance=context)

project/coplan/templates/base.html
{% load url from future %}

<!DOCTYPE html>
<!--[if lt IE 7 ]> <html dir="ltr" lang="en-US" class="ie6"> <![endif]-->
<!--[if IE 7 ]>    <html dir="ltr" lang="en-US" class="ie7"> <![endif]-->
<!--[if IE 8 ]>    <html dir="ltr" lang="en-US" class="ie8"> <![endif]-->
<!--[if IE 9 ]>    <html dir="ltr" lang="en-US" class="ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html dir="ltr" lang="en-US"> <!--<![endif]-->
  
  <head>
    <title>CoPlan</title>
    
    <meta charset="utf-8">
    <meta name="description" content="Local Community Plan-building Tool">
    <meta name="author" content="OpenPlans">
    
    <!--  Mobile Viewport Fix -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    
    <!-- Favicon & Progressively-Enhanced Touch Icons: 
	 http://mathiasbynens.be/notes/touch-icons#sizes -->
    <link rel="shortcut icon" href="/images/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="apple-touch-icon-144x144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="apple-touch-icon-114x114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="apple-touch-icon-72x72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="apple-touch-icon-precomposed.png">
    
    <link rel="stylesheet" href="{{ STATIC_URL }}coplan/css/style.css" type="text/css" media="screen, projection" />
    
    <!--[if lt IE 9]>
	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
	<![endif]-->
    
    <script src="{{ STATIC_URL }}libs/jquery.js"></script>
    <script src="{{ STATIC_URL }}libs/underscore.js"></script>
    <script src="{{ STATIC_URL }}libs/backbone.js"></script>
    <script src="{{ STATIC_URL }}libs/pretty.js"></script>
    {% block head_includes %}
    {% endblock head_includes %}
  </head>
  
  <body>
    <div id="page">
      
      <header id="branding" role="banner" class="clearfix">
	<div class="container">
          <h1 id="site-title"><span><a href="{% url 'home' %}" title="CoPlan" rel="home">CoPlan</a></span></h1>
          <nav id="user-menu" role="article">
            <ul>
	      {% if user.is_authenticated %}
              <li>Hi, {{ user.username }}. <a href="{% url 'logout' %}?next={{ request.build_absolute_uri }}" class="logout">Sign Out</a></li>
              <li><a href="{% url 'user_profile' user.pk %}">My Plans</a></li>
	      {% else %}
	      <li><a href="{% url 'socialauth_begin' 'twitter' %}?next={{ request.get_full_path }}">Sign In</a></li>
	      {% endif %}
            </ul>
          </nav>
	</div>
      </header><!-- #branding -->
      
      {% block content_wrapper %}
      <div id="content" class="container clearfix">
	
	{% block content %}
	{% endblock content %}
	
      </div><!-- #content -->
      {% endblock content_wrapper %}
      
    </div><!-- #page -->    
  </body>
</html>

project/coplan/templates/index.html
{% extends "base.html" %}
{% load url from future %}

{% block content_wrapper %}
<div class="splash">

  <div class="container clearfix">
    <div class="explanation-step step1">
      <div class="step-icon">
	<img src="{{ STATIC_URL }}coplan/img/idea.png"
	     title="&quot;Idea&quot; symbol  by The Noun Project, from thenounproject.com collection">
      </div>
      <div class="step-text">
	<h2>Share your idea</h2>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do 
	  eiusmod tempor incididunt ut labore et dolore</p>
      </div>
    </div>
    <div class="explanation-step step2">
      <div class="step-icon">
	<img src="{{ STATIC_URL }}coplan/img/discussion.png"
	     title="&quot;Community&quot; symbol by The Noun Project, from thenounproject.com collection">
      </div>
      <div class="step-text">
	<h2>Get feedback</h2>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do 
	  eiusmod tempor incididunt ut labore et dolore</p>
      </div>
    </div>
    <div class="explanation-step step3">
      <div class="step-icon">
	<img src="{{ STATIC_URL }}coplan/img/support.png"
	     title="&quot;Like&quot; symbol by Marwa Boukarim, from thenounproject.com collection">
      </div>
      <div class="step-text">
	<h2>Gather Support</h2>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do 
	  eiusmod tempor incididunt ut labore et dolore</p>
      </div>
    </div>
    
    <div class="splash-actions">
      <a href="{% url 'new_plan' %}">Create a new plan</a>
    </div>
  </div>

</div>

<div class="container clearfix">
  <h2>Featured plans</h2>
  {% for plan in featured_plans %}
  <div class="featured-plan">
    <a href="{% url 'edit_plan' plan.pk %}">
      {{ plan.title|default:'(No title yet)' }}</a>
    <p>{{ plan.owner.username }} made this plan because 
      &quot;{{ plan.motivation }}&quot;</p>
  </div>
  {% endfor %}
</div>
{% endblock %}

project/coplan/templates/plan_detail.html
{% extends "base.html" %}
{% load url from future %}

{% block head_includes %}
{% endblock %}

{% block content %}

<div id="plan-description">

  <div id="id_plan-form">

    <div class="plan-overview">
      <div class="field plan-title">
	{% if not plan.id or planner == plan.owner %}
	<input name="title" id="id_title" value="{{ plan.title }}" 
	       placeholder="Plan Title">
	{% else %}
	<div id="id_title">{{ plan.title }}</div>
	{% endif %}
      </div> <!-- plan-title -->

      <div class="plan-sub-overview">
	<div class="plan-owner">
	  {% if not plan.id or planner == plan.owner %}
	  <img class="avatar" src="{{ planner.avatar_url }}" />
	  {% else %}
	  <img class="avatar" src="{{ plan.owner.avatar_url }}"/>
	  {% endif %}
	</div> <!-- plan-owner -->
	
	<div class="field plan-motivation">
	  {% if not plan.id or planner == plan.owner %}
	  <div class="plan-motivation-label">
	    I am making this plan because:
	  </div>
	  <textarea name="motivation" id="id_motivation" 
		    placeholder="Why this plan is important to me...">{{ plan.motivation }}</textarea>
	  {% else %}
	  <div class="plan-motivation-label">
	    <a href="{% url 'user_profile' plan.owner.pk %}">{{ plan.owner.username }}</a> made this plan because:
	  </div>
	  <div id="id_motivation">{{ plan.motivation }}</div>
	{% endif %}
	</div> <!-- plan-motivation -->
      </div>

    </div>

    <div class="field plan-details">
      <h2>Plan Details</h2>

      {% if not plan.id or planner == plan.owner %}
      <textarea name="details" id="id_details" 
		placeholder="The plan details...">{{ plan.details }}</textarea>
      {% else %}
      <div id="id_details">{{ plan.details|linebreaks }}</div>
      {% endif %}
    </div>

  </div>

</div>

<div id="plan-info">
  <div id="map">
  </div>

  <div id="plan-supporting-documents">
    <h3>Supporting Documents</h3>
    
    {% if not plan.id or planner == plan.owner %}
    <div id="supporting-documents-form">
      <label for="">Link:</label>
      <input type="text" name="link-url" id="id_link-url" placeholder="http://">
      <button id="id_link-submit">+</button>
    </div>
    {% endif %}
    <ul class="links-list">
      <li class="resource-link hidden" id="link-template">
	<a href="#">The link title</a>
	<input type="hidden" name="link-id" value="...">
	{% if not plan.id or planner == plan.owner %}
	<button class="link-remove">-</button>
	{% endif %}
      </li>
      <li>
	(There are no supporting links yet)
      </li>
      <li><a href="#">facebook.com/lafayettepedplaza</a></li>
      <li><a href="#">lafayettepedplaza.org</a></li>
      <li><a href="#">flickr.com/lafpedplazagroup</a></li>
    </ul>
  </div>

</div>

<div id="discussion">
  <h3>Discussion</h3>
  <ol class="comments-list">
    <li class="comment like hidden" id="comment-template">
      <header>
      	<div class="comment-author vcard">
          <img class="avatar" src="http://placehold.it/40" />
	  <div class="comment-author-info">
      	    <a href="#" rel="author">Andy Cochran</a> <span class="comment-type">likes</span> this plan.
	  </div>
        </div><!-- .comment-author .vcard -->
      	<div class="comment-meta">
      	  <a href="#comment-1"><time pubdate="" datetime="2007-09-04T10:15:32+00:00">September 4, 2007 at 10:15 am</time></a>
    	</div><!-- .comment-meta -->
      </header>
      <div class="comment-body">
      	<p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. </p>
      </div>
    </li>
  </ol>

  <div class="comments-list">
    {% if user.is_authenticated %}
      <div class="comment-commenter">
	<img class="avatar" src="{{ planner.avatar_url }}" />
      </div>
      <div class="comment-content">
	<div class="comment-overview">
	  <a href="{% url 'user_profile' planner.pk %}">{{ planner.username }}</a>
	  <select id="id_comment-type">
	    <option value="1">likes</option>
	    <option value="-1">dislikes</option>
	    <option value="0">has a question about</option>
	  </select>
	  this plan
	</div>

	<div class="comment-text">
	  <textarea id="id_comment-text" placeholder="What do you think..."></textarea>
	</div>

	<div class="comment-submit">
	  <button id="id_comment-submit" disabled="disabled">Submit</button>
	</div>
      </div>
    {% else %}
      (You must be <a href="{% url 'socialauth_begin' 'twitter' %}?next={{ request.get_full_path }}">logged in</a> 
      to comment.)
    {% endif %}
  </div>
</div>

<div id="supporters">
  <div class="support-section">
    {% with plan.support.all as support %}

    {% if support|length == 1 %}
    <h3>1 citizen supports this plan</h3>
    {% elif support|length > 1 %}
    <h3>{{ support|length }} citizens support this plan</h3>
    {% endif %}

    <ul class="support-list">
      <li id="support-template" class="hidden support">
	<header>
      	  <div class="supporter vcard">
            <img class="avatar" src="{{ STATIC_URL }}coplan/img/user1.png" />
	    <div class="supporter-info">
      	      <a href="#" rel="author">Andy Cochran</a> supports this plan!
	      <span class="support-motivation">&quot;I live there&quot;.</span>
	    </div>
          </div><!-- .supporter .vcard -->
	</header>
      </li>
    </ul>

    {% endwith %}

    {% if user.is_authenticated %}
    <div id="current-user-support">
      <select name="motivation" id="id_support-motivation">
	<option>I live here</option>
	<option>I work here</option>
	<option>I play here</option>
      </select> and I 
      
      <span class="action">
	{% if planner in plan.supporters.all %}
	support this plan.
	{% else %}
	<button class="support-button" id="id_support-submit" type="button">Support this plan</button>
	{% endif %}
      </span>
    </div>
    
    {% else %}
    <p><a href="{% url 'socialauth_begin' 'twitter' %}?next={{ request.get_full_path }}">
	Log in</a> to show your support.</p>
    {% endif %}
    
  </div>
</div>

<script>
  {% if plan_data %}
  var planData = {{ plan_data|safe }};
  {% else %}
  var planData = {owner: {{ planner.pk|default:"-1" }} };
  {% endif %}

  var Coplan = Coplan || {};
  Coplan.planUrlRoot = '{% url "plan_list" %}';
  {% if user.is_authenticated %}
  Coplan.currentUserId = {{ planner.pk }};
  {% endif %}
</script>

<script src="{{ STATIC_URL }}coplan/js/models.js"></script>
<script src="{{ STATIC_URL }}coplan/js/views.js"></script>

<script>
  var plan = new Coplan.Plan(planData);
  var planView = new Coplan.PlanView({model: plan});
</script>

{% endblock %}

project/coplan/templates/user_profile.html
{% extends "base.html" %}
{% load url from future %}

{% block head_includes %}
{% endblock %}

{% block content %}

<div id="plan-listing">

  <h1>Plans belonging to {{ owner.username }}</h1>

  <ul>
    {% for plan in owner.owned_plans.all %}
    <li><a href="{% url 'edit_plan' plan.pk %}">{{ plan.title }}</a></li>
    {% endfor %}
  </ul>

</div>

{% endblock %}

project/project/templates/login-form.html
{% extends "base.html" %}

{% block content %}
<div>
  <a href="{% url socialauth_begin 'twitter' %}?next={{ request.GET.next }}">Please log in with twitter</a>
</div>
{% endblock content %}